# ----------------------------------------------------------------------------------------------------
# Pipeline to deploy Alerts and alert groups for multiple environments
# ----------------------------------------------------------------------------------------------------
# This needs the variable group "TrafficControlDemo" - see readme.md for details.
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'ubuntu-latest'
# ----------------------------------------------------------------------------------------------------
trigger: none

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/alerts-only-pipe.yml
  parameters:
    environments: ['DEMO']
    variableGroupName: 'TrafficControlDemo'
    bicepFolderName: '.azdo/bicep'
    bicepFileName: 'main-alerts.bicep'
