trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'FineCollectionService - BUILD'
  
variables:
  - group: dapr-traffic-control-demo

stages:

 - stage: CI
   displayName: CI Stage 
   variables:
     kubernetesCluster: 'rutzsco-aks1'
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: 'ubuntu-latest'   
      
     strategy:
        runOnce:
          deploy:
  
            steps:

            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                kubernetesServiceConnection: 'rutzsco-aks1'
                namespace: 'dapr-traffic-control'
                manifests: '$(Pipeline.Workspace)/build/Deploy/deployment.yaml'
                containers: 'rutzscolabcr.azurecr.io/dapr-traffic-control/finecollectionservice:$(resources.pipeline.build.runName)'