trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'TrafficControlService - BUILD'
  
variables:
  - group: dapr-traffic-control-demo
  - name: containerImage
    value: '$(acrName).azurecr.io/dapr-traffic-control/trafficcontrolservice:$(resources.pipeline.build.runName)'
  - name: templateFile
    value: '$(Pipeline.Workspace)/build/Deploy/main.bicep'

stages:

 - stage: CI
   displayName: CI Stage 
   variables:
     kubernetesCluster: 'rutzsco-aks1'
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: 'ubuntu-latest'   
      
     strategy:
        runOnce:
          deploy:
            steps:

            - task: AzureCLI@2
              displayName: Deploy trafficcontrolservice
              inputs:
                azureSubscription: $(azureServiceConnection)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters containerImage=$(containerImage) envName=$(acaEnvironmentName) acrName=$(acrName) acrUsername=$(acrUsername) acrPassword=$(acrPassword) > outputs.json