apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: ${REDIS_HOST}
  - name: redisPassword
    secretKeyRef:
      name: dapr-traffic-control-redis
      key:  redisPassword
  - name: actorStateStore
    value: true
  - name: enableTLS
    value: true
auth:
  secretStore: secret-store
scopes:
  - trafficcontrolservice