trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/VehicleRegistrationService/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  rootDirectory: 'src/VehicleRegistrationService'
  dockerRegistryServiceConnection: 'aefdd2ab-f2b0-4625-ace6-1625a6ed13ec'
  dockerRegistryServiceConnectionMFGP: 'c0aa6da8-718a-4385-b2d0-2f802e39a565'
  dockerImageRepository: 'dapr-traffic-control/VehicleRegistrationService'
  dockerFilePath: '$(Build.SourcesDirectory)/$(rootDirectory)/Dockerfile'
  dockerImageTag: '$(Build.BuildNumber)'

steps:

- task: Docker@2
  displayName: 'Container - Build and push'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(dockerImageRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerFilePath)'
    buildContext: '$(Build.SourcesDirectory)/$(rootDirectory)/'
    tags: |
      $(dockerImageTag)
      latest
- task: Docker@2
  displayName: 'Container - Build and push MFG Playground'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnectionMFGP)'
    repository: '$(dockerImageRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerFilePath)'
    buildContext: '$(Build.SourcesDirectory)/$(rootDirectory)/'
    tags: |
      $(dockerImageTag)
      latest
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/$(rootDirectory)/deploy/'
    artifact: 'Deploy'
    publishLocation: 'pipeline'